#!/bin/bash
#
# Get an access token for an app
#
appId=""
appSecret="" # Get this from config.ini
curl -X GET "https://graph.facebook.com/oauth/access_token
  ?client_id=$appId
  &client_secret=$appSecret
  &grant_type=client_credentials"
