<?php
$products = array( "product-9" => "RE - BUZZ ($69)",
		   			"product-12" => "RE - BUZZ ($69)",
                   	"product-13" => "RE - IMPACT ($99)",
                   	"product-14" => "RE - IMPACT ($99)",
                   	"product-15" => "RE - IMPACT ($99)",
                   	"product-16" => "RE - IMPACT ($99)",
                   	"product-17" => "RE - IMPACT ($99)",
	                "product-19" => "RE - IMPACT ($99)",
	                "product-21" => "RE - IMPACT ($99)",
                   	"product-22" => "RE - BUZZ ($69)",
                   	"product-24" => "RE - 14 DAY TREE TRIAL",
                   	"product-29" => "RE - 14 DAY FREE TRIAL",
					"product-46" => "TNT SPEARMAN REALTYONE- IMPACT DEFAULT",
					"product-47" => "TNT SPEARMAN REALTYONE- IMPACT DEFAULT",
					"product-48" => "TNT SPEARMAN REALTYONE- GROWTH DEFAULT",
					"product-49" => "TNT SPEARMAN REALTYONE- GROWTH DEFAULT",
					"product-50" => "TNT SPEARMAN REALTYONE- BUZZ DEFAULT",
					"product-51" => "TNT SPEARMAN REALTYONE- BUZZ DEFAULT",
					"product-52" => "TNT SPEARMAN REALTYONE- TRIAL DEFAULT",
					"product-53" => "RE - IMPACT ($99)",
					"product-55" => "RE - IMPACT ($99)",
                        "product-58" => "AGENT LEADER IMPACT $89",
                        "product-59" => "AGENT LEADER BUZZ $69",
                        "product-60" => "AGENT LEADER IMPACT $89",
                        "product-61" => "AGENT LEADER BUZZ $69" ,
                        "product-62" => "RE - IMPACT ($99)",
                        "product-63" => "RE - BUZZ ($69)",
												"product-64" => "RE - IMPACT ($99)",
											  "product-65" => "RE - IMPACT ($99)",
												"product-66" => "RE - IMPACT ($99)",
												"product-72" => "RE - IMPACT ($99)"
											  )
?>
