<?php
$config['RAILS_ENV']='development';
$config['RAILS_USER']='woo';
$config['RAILS_USERID']='jwooten37830@mac.com';
$config['RAILS_PASSWORD']='random1';
$config['MAIL_HOST']='localhost:3000';
$config['EMAIL_FROM']=$config['RAILS_USERID'];
$config['SENDMAIL_SERVER']='smtp.gmail.com';
$config['SENDMAIL_PORT']='587';
$config['SENDMAIL_USERNAME']='wooten.666@gmail.com';
$config['SENDMAIL_PASSWORD']='Fester1.';
$config['ISSUES_SERVER']='https://github.com/woo37830/blog/issues';
$config['PATTI_ISSUES_SERVER']='https://github.com/woo37830/patti_rails/issues';
$config['PATTI_DOCUMENTS']='https://jwooten37830.com/patti/webhook/documentation/Documentation.html';
$config['PATTI_DATABASE_SERVER']='jwooten37830.com';
$config['PATTI_DATABASE_USER']='root';
$config['PATTI_DATABASE_PASSWORD']='random1';
$config['PATTI_DATABASE']='users_db';
$config['PATTI_LOG_TABLE']='logs';
$config['PATTI_USERS_TABLE']='users';
$config['NOTES_SERVER']='https://jwooten37830.com/wiki/projects/blogdiscussions/Blog_Discussions.html';
$config['MSG_USER']='4K9vV0InIxP5znCa7d';
$config['MSG_PASSWORD']='ie6n85dF826iYe5npA';
$config['THRIVECART_SECRET']='IEYDASLZ8FR7';
?>
